### ISSUE TITLE
Check misses raw directive

### ISSUE THREAD

**Issue by di** [pypa/readme_renderer#100]
From https://github.com/pypa/warehouse/issues/3785, readme_renderer is not raising an error when the raw directive is present.

**Comment by westurner** [comment]
``SETTINGS`` 
includes

```python
    # Prevent local files from being included into the rendered output.
    # This is a security concern because people can insert files
    # that are part of the system, such as /etc/passwd.
    "file_insertion_enabled": False,
...
    # Disable raw html as enabling it is a security risk, we do not want
    # people to be able to include any old HTML in the final output.
    "raw_enabled": False,
```
https://github.com/pypa/readme_renderer/blob/master/readme_renderer/rst.py

What command invocation are you using with which file that's not stripping the ``.. raw::`` directives?

**Comment by di** [comment]
This issue is about whether the `python setup.py check -r -s` fails when the raw directive is present in a description, not about whether it's allowed when rendering (it isn't).

**Comment by westurner** [comment]
With ``--no-raw``, a warning is emitted to the warning stream and also written to the document.

http://docutils.sourceforge.net/docs/user/config.html#warning-stream

AFAIU, you would need to parse the warning stream in order to detect this error.

**Comment by jonparrott** [comment]
I've been pretty close to this code recently. I'll try to fix this during Monday's sprint.

**Comment by brainwane** [comment]
@theacodes can you share any thoughts in case anyone else would like to fix it? Or do you think you might get to it this week?

**Comment by theacodes** [comment]
The most useful thing right now is creating a test that replicates this.

**Comment by theacodes** [comment]
Okay, based on my testing we *do* indeed warn and error when the raw directive is present:

```
running check
warning: Check: The project's long_description has invalid markup which will not be rendered on PyPI. The following syntax errors were detected:
line 7: Warning: "raw" directive disabled.
```

I have created a pull request (https://github.com/pypa/readme_renderer/pull/103) to add test cases explicitly for this, but this seems to be working as intended.
