### ISSUE TITLE
RST accepted by readme_renderer, but failing to upload to PyPI

### ISSUE THREAD

**Issue by stuhood** [pypa/readme_renderer#108]
On Friday night we saw a failure to upload to PyPI (https://github.com/pantsbuild/pants/issues/5874) with the following error:

> HTTPError: 400 Client Error: The description failed to render in the default format of reStructuredText. See https://pypi.org/help/#description-content-type for more information. for url: https://upload.pypi.org/legacy/

I've just confirmed that `readme_renderer.rst.render(..)` for [the relevant file](https://github.com/pantsbuild/pants/blob/master/src/python/pants/notes/master.rst) succeeds (although it takes a while to render).

----

Are there additional requirements for PyPI upload beyond what is applied by this package? Obviously the file is quite large, and my first "guess and check" approach was going to be to truncate it. But having this package fail reproducibly the same way PyPI would would help folks debugging upload issues.

**Comment by theacodes** [comment]
See upstream issue https://github.com/pypa/warehouse/issues/4079
