### ISSUE TITLE
Untraceable error

### ISSUE THREAD

**Issue by cefn** [pypa/readme_renderer#109]
I just ran the setup.py check on [my source](https://github.com/vgkits/vgkits-vanguard/blob/b9d769cd911ad685f0d900608fc49b0ff2b1145d/setup.py)

It resulted in the following mystifying error, which indicates no line, source or identifiable structure to investigate and fix...

```
$ python3 setup.py check -r -s
running check
warning: Check: The project's long_description has invalid markup which will not be rendered on PyPI. The following syntax errors were detected:
line : Error: Anonymous hyperlink mismatch: 1 references but 0 targets.
See "backrefs" attribute for IDs.
``` 

How do I proceed to identify where and what the error actually is?

**Comment by di** [comment]
Agreed, the error message is not great, but it comes from [docutils](http://docutils.sourceforge.net/) so it is somewhat out of the control of `readme_renderer`.

The error means that somewhere you have a link reference, but there is not a target for that link.

The issue is this link in your `CHANGES.rst`:

```
`click<http://click.pocoo.org/>`__
```

You need a space between the reference and the target URI:

```
`click <http://click.pocoo.org/>`__
```

**Comment by cefn** [comment]
Finding the bug in the content on my behalf is incredibly helpful and goes above and beyond the call of duty. Thanks for that. 

Sorry not to have reported the error-reporting issue in the right place. 

I was working through removing the need for .rst which I really struggle with, (ideally replacing it with GFM markdown). However, I found that pip 9 seems to die on the new setup(...) field...

```
long_description_content_type="text/markdown",
```

...so the fact it was working on my machine was an artefact of running pip 10. 

Requiring pip 10 would force all future debian-ish users of my library to upgrade their pip install before using the library. This is gnarly, so I am probably heading back to using .rst again.

Figuring out how to get sane error reports is therefore critical again given how incredibly fragile the .rst language seems to be to whitespace issues.

**Comment by cefn** [comment]
To clarify for anyone seeing this issue, it seems like the issue with pip 9 was a warning message As described at https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi

> Unknown distribution option: 'long_description_content_type'

and it was coincidentally presented in the build log, which had another failure elsewhere in the package. The warning message wasn't the reason for the failure, so indeed Markdown-based packages should be fine to be installed with pip9.
