### ISSUE TITLE
Add command to check a file

### ISSUE THREAD

**Issue by merwok** [pypa/readme_renderer#127]
I would like an entry-point to check a reST or markdown file.

(I’ve heard about twine check but it doesn’t work for me due to flit-tox mismatch.)

**Comment by di** [comment]
More details:
* https://github.com/takluyver/flit/issues/216
* https://github.com/pypa/twine/pull/412

**Comment by merwok** [comment]
I am using the recent PEP 517 integration in tox, so tox reads my build-deps in pyproject.toml and uses flit to install my project.  This works well, even for a Python2.7 test env!  (I do need to change my lint/test commands to run against the installed project rather than the files in the repo root, but that’s not a new issue.)

Now `twine check` wants a `path/to/dists` argument.

Idea 1: check `.tox/dist`, but that only contains the sdist, and I run into https://github.com/takluyver/flit/issues/216

Idea 2: run `pip wheel` (as done by other projects), but I don’t have a setup.py anymore

Idea 3: run `flit build`, but I don’t want the files created in `repo-root/dist` (https://github.com/takluyver/flit/issues/217)

**Comment by merwok** [comment]
Ideally I would not use the top-level `dist` directory to create and check the dists (idea 3, takluyver/flit#217), but in the meantime I’ll take `twine check dist/*`.

Feel free to close, at least I got the opportunity to detangle the various issues and this provides a record of the discussion with links.

**Comment by di** [comment]
Great. Closing as I don't think there's anything `readme_renderer` needs to do here.
