### ISSUE TITLE
Support standard rst admonitions

### ISSUE THREAD

**Issue by anntzer** [pypa/readme_renderer#132]
rst provides standard "admonitions" (http://docutils.sourceforge.net/docs/ref/rst/directives.html#admonitions) such as
```
.. note::
   Hello world!
```
which gets rendered by default (by rst2html) as
![screenshot_20181024_142909](https://user-images.githubusercontent.com/1322974/47430333-486ef700-d799-11e8-96b1-06cb674c67cb.png)
but readme_renderer just yields two paragraphs with no markup at all
```
<div>
<p>Note</p>
<p>Hello, world!</p>
</div>
```

It would be nice if admonitions were supported.
Perhaps related to #120.

**Comment by kdeldycke** [comment]
This is a great feature to support. It allows package maintainer to display big warning for major package update or breaking changes.

For instance, I use a `.. DANGER::` admonition at the very top of my package to announce a renaming:
* https://github.com/kdeldycke/maildir-deduplicate/commit/ebfafa153562e093fb060df7d44999b327bfa93d
* https://pypi.org/project/maildir-deduplicate/2.2.0/

**Comment by stuij** [comment]
I'm just adding a +1 for this feature. We have a lot of notes in our ABI docs (current docs up on Github and future docs that will be added), and right now the rendering of them on Github is confusing because of this:

https://github.com/ARM-software/abi-aa

Can we expect any chance of this being supported? It would be really appreciated.

**Comment by pzhlkj6612** [comment]
Hi @stuij .

> We have a lot of notes in our ABI docs (current docs up on Github and future docs that will be added), and right now the rendering of them on Github is confusing because of this...

Since you mentioned GitHub, I think that what you said is not related to this issue or even this repo. You could have a look at https://github.com/github/markup/issues/68 .
