### ISSUE TITLE
Warning message says to install readme_render[md] but cmarkgfm must be installed

### ISSUE THREAD

**Issue by kpinc** [pypa/readme_renderer#133]
This is something of an FYI because I'm not clear on what is really supposed to happen.

I tried running "twine check" and got a message that the README.rst could not be checked and that 'readme_render[md]' needed to be installed.  But it seems that what needs to be installed is cmarkgfm.

The message is coming from readme_renderer.  (Seemingly markdown.py line 28.)

FWIW, setup.py does not install_requires cmarkgfm either.

Thanks for listening.

**Comment by di** [comment]
Thanks @kpinc, I think I know what's happening here. The warning can be ignored.

**Comment by mmerickel** [comment]
Note also that it's `readme_renderer[md]`, not `readme_render[md]`. 

I also opened https://github.com/pypa/twine/issues/420 related to its misuse of the new optional support for markdown in readme_renderer.

**Comment by di** [comment]
We'll fix this in `twine` with https://github.com/pypa/twine/pull/421.
