### ISSUE TITLE
Officially support Python 3.7

### ISSUE THREAD

**Issue by di** [pypa/readme_renderer#135]
- [ ] Test against 3.7
- [ ] Add Python 3.7 classifier

**Comment by pganssle** [comment]
Note that for adding Python 3.7 tests on Travis, you need to use the `xenial` distribution, see, e.g. [this PR](https://github.com/pypa/packaging/pull/138/files#diff-354f30a63fb0907d4ad57269548329e3R14) or [this one](https://github.com/dateutil/dateutil/pull/784/files).

**Comment by crwilcox** [comment]
@di to close
