### ISSUE TITLE
Official PyPI way to render strikethru in .rst description?

### ISSUE THREAD

**Issue by pfalcon** [pypa/readme_renderer#141]
**Describe the bug**

I'm unable to render strike-thru text in long_description in reStructuredText: https://pypi.org/project/picoweb/1.5/ . Given that there's no builtin strike-thru support in .rst (big-big sigh), I was using one of the methods described in https://stackoverflow.com/questions/15989218/how-to-do-strikethrough-in-a-restructuredtext-file-hosted-on-github , that happened to be:

~~~
.. raw:: html

   <strike>
~~~

Well, that doesn't work with PyPI. And I hope I can be kindly guided re: what would work. I both tried to search on google regarding that, and here in bug tracker, in vain.

Keywords for search: strikethru, strike

**Expected behavior**

I hope I can render strikethru.

**To Reproduce**
URL: https://pypi.org/project/picoweb/1.5/

Problem spot is:
~~~
.. raw:: html

   <strike>

Paragraph of text.

.. raw:: html

   </strike>
~~~

**Comment by di** [comment]
Moved this issue to [pypa/readme_renderer](https://github.com/pypa/readme_renderer).

The `raw` directive is not supported, so if there's not a standard way to do this with rST, it seems unlikely that it will be possible.

This isn't a real answer to your question, but are you aware that you can write your description in Markdown instead, which does support strikethrough?

**Comment by dstufft** [comment]
We might be able to support the raw directive unless it takes a file or something. We're not relying on rst producing good HTML anymore since we have bleach.

**Comment by miketheman** [comment]
Reviewing older issues. `<strike>` is no longer the recommended way to represent struck text. See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/strike
Preferred are `<del>` and `<s>` - but still nothing specific in docutils. We currently allow the `del` attribute through our sanitizer, so this works:

```rst
.. role:: del

:del:`This text is crossed out`
```

turns into:

```html
<p><del>This text is crossed out</del></p>
```

With the appropriate changes on the warehouse CSS side, this would render as desired.

From a portability perspective, as a custom RST role it'd have to be implemented in any system using it. There's a [Sphinx extension](https://sphinx.silverrainz.me/strike/) that conforms to `del` as well.

**Comment by miketheman** [comment]
Double-checked this today, and it turns out that we don't need any explicit CSS on warehouse unless we want it, because the major browsers support `del` natively already! 🎉
