### ISSUE TITLE
No need for a warning about markdown renderers

### ISSUE THREAD

**Issue by nedbat** [pypa/readme_renderer#142]
I have no markdown files in my project, yet when I run "twine check dist/*", I get a warning about "Markdown renderers are not available."  The code looks like it will already issue this warning if markdown is used, so why also issue it on import?  This just adds needless noise to projects that don't use markdown.

**Comment by di** [comment]
This is fixed in https://github.com/pypa/twine/pull/421 but hasn't been released yet.

**Comment by brainwane** [comment]
[Fix is now released!](https://pypi.org/project/twine/1.13.0/)
