### ISSUE TITLE
reStructuredText header issue

### ISSUE THREAD

**Issue by dgasaway** [pypa/readme_renderer#144]
I was testing a new project (new to PyPI) by uploading to TestPyPI.  I have a README.rst file that is read into long_description.  The README looked fine in bitbucket, passed readme_renderer and rst-lint, but kept failing to render formatted in the project description on TestPyPI.  After tinkering for hours, I chopped up the file and kept adding more pieces until the failure came back, and it came down to a header that looked like this...

```
From Source
-----------
```

And then I noticed that in the (unformatted) project description on TestPyPI, it would strangely render with a greater than symbol in front...

```
>From Source
-----------
```
I made sure there were no special characters in that position in the file.  Deleted everything between this and the text before it.  Looked good.  Eventually, I just changed the header, and the problem went away.

**Comment by jamadden** [comment]
This reminds me of 
https://github.com/pypa/wheel/issues/178

**Comment by di** [comment]
Sounds similar. Perhaps we need to fix this farther upstream then, rather than in `readme_renderer`.

**Comment by dgasaway** [comment]
If you're still looking for feedback from me (sorry), I tried it again with a new project I was working on today.  Did not have a problem.

**Comment by brainwane** [comment]
Since you could not reproduce the problem, I am going to close this, @dgasaway -- thank you for the report, and glad it's resolved!

Other people in the future should feel free to re-open this if the problem recurs.
