### ISSUE TITLE
Error: Unknown interpreted text role "kbd".

### ISSUE THREAD

**Issue by billop** [pypa/readme_renderer#148]
**Describe the bug**

:kbd: in rst file is not recognized by pypi

**Expected behavior**

:kbd: in rst file should be recognized by pypi
**To Reproduce**

- Set long_description in setup.py to a reStructuredText document containing `` :kbd:`Hello World` ``
- `python setup.py sdist`
- `twine check dist/*`

**Additional context**
":kbd:" in rst files is supported by Gitlab, Github, readthedocs, etc. However I've noticed that restview does not support it.

**Comment by McSinyx** [comment]
I stumbled upon this when flit refuses to build when README.rst uses the kbd role.  I took a deeper look and it seems that the proposal for this over docutils (which readme_renderer uses to render, ehm, READMEs) [has yet to be accepted](https://sourceforge.net/p/docutils/mailman/docutils-users/thread/b6293799-fad7-660f-de77-a2e4c83b2faf@gmail.com/).

I suppose we can either use Sphinx as the reST backend for readme_renderer or to document about the lack of support the kbd role on PyPI.  Personally I'm fine without these solutions though.

**Comment by miketheman** [comment]
Looks like docutils added kbd in 0.17 https://docutils.sourceforge.io/HISTORY.html#release-0-17-2021-04-03

The support appears to be part of the HTML5 writer, so it’s worth testing the behavior today or whether this relies on updating our writer to use html5 as well. #249

**Comment by miketheman** [comment]
Looks like I was incorrect in my assertion about html5 - it's already supported today, with a little extra effort.

The current `readme_renderer` will support the `kbd` role **if you declare a custom role in your rst**, per the current `docutils` behavior.
Example:

```rst
My Package
==========

.. role:: kbd

Type :kbd:`Ctrl+C` to quit
```

will output this HTML:

```html
<p>Type <span class="kbd">Ctrl+C</span> to quit.</p>
```

And the [current Warehouse CSS](https://github.com/pypi/warehouse/blob/39daea188d2e1e6494c50753cd48cb5a8da3e8c4/warehouse/static/sass/base/_typography.scss#L40) should pick that up and render as code.

TL,DR: It looks like all you'd have to do is add `.. role:: kbd` in your RST for this to work.

**Comment by miketheman** [comment]
Closing, as there's no action for us to take here right now.
