### ISSUE TITLE
`twine check` passes, rst doesn't render on pypi

### ISSUE THREAD

**Issue by lzkelley** [pypa/readme_renderer#153]
Similar to [this issue](https://github.com/pypa/readme_renderer/issues/115) my `twine check dist/*` command passes without any warnings or errors, but my `README.rst` is still failing to render on `pypi`: [test.pypi package here](https://test.pypi.org/project/kalepy/0.1.3b0/).  Unlike the linked issue, my readme doesn't use any math or external configuration files (etc).  I'm not sure what else to do to debug this...  any help appreciated, thanks!

**Comment by di** [comment]
@lzkelley Your TestPyPI package looks like your description is formatted with Markdown, not reStructuredText.

**Comment by lzkelley** [comment]
@di Ugh, facepalm; so sorry.  Thank you!
Is there any way to scrub an `issue` from all of the internet?!
