### ISSUE TITLE
ReST field list renders with spurious cell

### ISSUE THREAD

**Issue by Lx** [pypa/readme_renderer#155]
[My `README.rst` file](https://raw.githubusercontent.com/Lx/python-rosteron/master/README.rst) contains the following snippet:

```
Source code
^^^^^^^^^^^

Pull requests are gratefully received and considered.

:GitHub repository: https://github.com/Lx/python-rosteron
```

which renders [on GitHub](https://github.com/Lx/python-rosteron/blob/master/README.rst) like this:

<img width="497" alt="rendered ReST on GitHub" src="https://user-images.githubusercontent.com/160164/59253740-37b0ba00-8c72-11e9-998e-3e2e77e3c3ef.png">

but renders [on PyPI](https://pypi.org/project/rosteron/) like this:

<img width="804" alt="rendered ReST on PyPI" src="https://user-images.githubusercontent.com/160164/59253692-210a6300-8c72-11e9-8a64-ec5395ada8ba.png">

It's not a CSS issue—an extra table cell with an `&nsbp;` is being generated:

```
<table>
    <col>
    <col>
    <tbody>
        <tr>
            <th>GitHub repository:
        </tr>
        <tr>
            <td>&nbsp;
            <td><a href="https://github.com/Lx/python-rosteron" rel=nofollow>https://github.com/Lx/python-rosteron</a>
            </td>
        </tr>
    </tbody>
</table>
```

(The intermittent lack of `</th>` and `</td>` is not a typo.)

**Comment by Lx** [comment]
This issue additionally exists here:
https://pypi.org/project/metlinkpid/

**Comment by mondeja** [comment]
Reported with minimal reproducible example in [docutils bug tracker](https://sourceforge.net/p/docutils/bugs/439/).

**Comment by Lx** [comment]
I note that a fix is pushed but my documents on PyPI are still currently affected.  Would it be more appropriate to keep this issue open until the fix propagates to the site?

**Comment by di** [comment]
The fix was pushed to PyPI in https://github.com/pypa/warehouse/pull/10480. PyPI will eventually re-render your projects description with the new version of this library, but this happens slowly, in batches, over a period of time.
