### ISSUE TITLE
Status of markdown support

### ISSUE THREAD

**Issue by ulope** [pypa/readme_renderer#156]
The README claims that this module supports markdown:
https://github.com/pypa/readme_renderer/blob/7bf7529296acfa7db0edf7914cb4571d691b63ee/README.rst#L6 
#55 seems to support this. 
Yet looking at the code there seems to be no way to actually invoke the markdown render check.

Is that an oversight, or was markdown support removed again without updating the readme?

**Comment by di** [comment]
There's nothing to "check" for a Markdown readme as they will gracefully fail if there's invalid syntax, unlike reStructuredText. Any markdown readme will always be accepted by PyPI.

**Comment by ulope** [comment]
Ok fair enough.

The README should probably be updated to remove the reference to markdown then.

**Comment by di** [comment]
This project still supports _rendering_ Markdown, which is it's primary purpose.
