### ISSUE TITLE
Add type annotations

### ISSUE THREAD

**Issue by bhrutledge** [pypa/readme_renderer#166]
I've been working on adding type annotations to Twine (https://github.com/pypa/twine/issues/231), and readmer_renderer is one of our imports that's missing type hints/stubs. Is there any interest in adding those, either in the source or to https://github.com/python/typeshed?

See also: https://mypy.readthedocs.io/en/stable/existing_code.html

**Comment by di** [comment]
Yes! In the source would be fine.

**Comment by di** [comment]
FYI @bhrutledge, @miketheman has created #225 to address this if you wanted to review.
