### ISSUE TITLE
Add suport for math expressions

### ISSUE THREAD

**Issue by ThomasTNO** [pypa/readme_renderer#214]
It would be interesting if we could add support for math expressions, in line with the GitLab flavored markdown.
https://docs.gitlab.com/ee/user/markdown.html#math

**Comment by miketheman** [comment]
Thanks for the suggestion! This renderer relies heavily on https://github.com/theacodes/cmarkgfm , which in turn relies on https://github.com/github/cmark-gfm - and that syntax would need to support math , not this renderer.

See https://github.com/github/cmark-gfm/issues/6 and https://github.com/commonmark/cmark/issues/439 for upstream issues.
