### ISSUE TITLE
"Requires: Python >=3.6" metadata missing on Pypi, despite being in setup.py

### ISSUE THREAD

**Issue by vphilippon** [pypa/readme_renderer#215]
Hello!

I see that the `python_requires=">=3.6"` is there in the setup.py, but if you look on Pypi, the "Requires: Python >=3.6" metadata is missing.
See https://pypi.org/project/readme-renderer/30.0/
And this is not only a visual bug: My recent enough version of pip on Python 2.7 (20.3.4, so aware of pypi metadata) will hapilly install `readme-renderer 30.0` (ex: when installing `twine` :) ).

I'm not 100% sure of the cause, but in other projects I've seen this happen when the pipeline (or the maintainer) was using an outdated version of `twine` IIRC (although you're all likely more aware of how this works than me :P ).

In terms of impact right now, `twine 1.15.0` (my main usage example, latest version supporting py2.7) still works even with the "unsupported" `readme-renderer 30.0` installed. So nothing seems on fire at the moment from my POV.
Still something worth adressing for the future I think.

Let me know if I can help with any more details.
Cheers and good luck!

**Comment by vphilippon** [comment]
Bonus:
If you can manage to somehow update correctly the metadata on pypi, instead of publishing a `30.1` and yank `29.0` and `30.0`, it would be a wonderful gift for me.

If not, that's ok, no worries, that situation I have is on me.

(For your potential curiosity: I'm stuck in a position where I am still using `devpi<6` (for unfortunate reasons), which didn't recognize the yank metadata, and that's in no way your responsibility. But if in this very specific case the metadata can be updated by a republish or something, since the property is there in the code, I'd be saved a pass through a bunch of projects on my end to put a bunch of downpins :) .)

**Comment by miketheman** [comment]
This appears to have been resolved via https://github.com/pypa/readme_renderer/pull/204 and was released in version 31.0.

On https://pypi.org/project/readme-renderer/31.0/ : 

<img width="231" alt="Screen Shot 2022-03-11 at 8 03 06 AM" src="https://user-images.githubusercontent.com/529516/157871608-48c82a00-ed86-4f83-93d6-5e09859a3924.png">

is displayed - previously there was no requirement.

Versions prior to 31.0 did not have this requirement set, so it makes sense that twine would behave as it did.

Recommend closing this issue.
