### ISSUE TITLE
Support cmarkgfm 0.8

### ISSUE THREAD

**Issue by gustaphe** [pypa/readme_renderer#240]
I'm having the same issue that was solved by #209 , but for `'cmarkgfm>=0.8.0`. I wouldn't know how to test things because I don't know python, but presumably the same change as that PR should do the trick.

**Comment by di** [comment]
Hi @gustaphe, what exactly is the issue you're having?

**Comment by gustaphe** [comment]
Running `plover` from package `plover-git`, with package `plover_plugins_manager` installed on Arch Linux, gives this error message
```
2022-04-26 10:27:56,648 [MainThread] ERROR: error loading gui.qt.tool plugin: plugins_manager (from plover_plugins_manager.gui_qt.manager)
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/plover/registry.py", line 56, in register_plugin_from_entrypoint
    obj = entrypoint.load()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2464, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2487, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 782, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (cmarkgfm 0.7.0 (/usr/lib/python3.10/site-packages), Requirement.parse('cmarkgfm>=0.8.0'), {'readme-renderer'})
```

The [AUR listing for the latter package](https://aur.archlinux.org/packages/plover_plugins_manager) has a previous issue with the same error, which spawned #209. 
I have no insight into what drives the requirements race on the other end. Sorry if this is X/Y.

**Comment by di** [comment]
Unfortunately I don't think there's anything we can do here, whatever is installing `cmarkgfm=0.7.0` alongside the latest version of `readme-renderer` needs updated to install `cmarkgfm>=0.8.0` instead. Sorry but I'm not familiar enough with the Arch ecosystem to know where to point you.

**Comment by gustaphe** [comment]
Sorry, I realize now this error goes the other way around. I'll try to get that package to update.
