### ISSUE TITLE
Timeline for next release

### ISSUE THREAD

**Issue by jharwell** [pypa/readme_renderer#250]
I've hit #115 hard in my pypi project, and it looks like this has been fixed in #246. Looking at the past timeline of release, it looks like there is one every 4 months or so. The last release was in April, so I'm wondering when we can expect the next release? Trying to decide if I need to remove the math from my README, or if I can just wait a week or two for things to work.

Thanks!

**Comment by miketheman** [comment]
Hey @jharwell !
Follow this PR for the release: #248
I'm testing a few things out to see if the changes actually do the thing I expect them to do before proceeding.

**Comment by di** [comment]
New version has been released: https://pypi.org/project/readme-renderer/36.0/

Thanks @miketheman for your work here!
