### ISSUE TITLE
Escaped HTML visible in package description on pypi.org

### ISSUE THREAD

**Issue by sergei-maertens** [pypa/readme_renderer#258]
(copied from https://github.com/pypi/warehouse/issues/12162, where I got forwarded to this repo)

**Describe the bug**

After publishing the package, there is some escaped HTML visible:

```
<nav class="contents" id="contents">
(table of contens, rendered properly)
</nav>
```

Seeing this with these projects: 

* https://pypi.org/project/zgw-consumers/
* https://pypi.org/project/django-simple-certmanager/

I suspect that something is going wrong with the `contents::`` rst directive, but I can't guarantee this.

**Expected behavior**

No HTML should be visible, instead pypi.org should properly convert the rst into HTML.

**To Reproduce**

* https://pypi.org/project/zgw-consumers/, with readme file: https://github.com/maykinmedia/zgw-consumers/blob/main/README.rst
* https://pypi.org/project/django-simple-certmanager/, with readme file: https://github.com/maykinmedia/django-simple-certmanager/blob/main/README.rst

**My Platform**

* Brave 1.42.88 (Chromium 104.0.5112.81)
* Packages published using the official Github action
* Package built on Github CI with the latest setuptools/wheel that's available (`pip install pip setuptools wheel --upgrade`)

**Additional context**

I cannot reproduce this using any of the `rst2htmlX.py` scripts in my virtualenv.

**Comment by miketheman** [comment]
Thanks for the report! This may have been induced by the recent change from html4 to html5 and the new semantic HTML tag wasn't allowed through our Bleach filter.
We don't currently have a test for this directive, so apologies it was overlooked.

**Comment by sergei-maertens** [comment]
Thank you for the swift resolution!
