### ISSUE TITLE
Support rst include directive

### ISSUE THREAD

**Issue by j3mdamas** [pypa/readme_renderer#268]
If the reasoning being the security issues, specifically with include directive, is what is described on [here](https://github.com/pypa/readme_renderer/blob/da1a5a461c2cf668b83027e65b7d92b11a3f91d4/readme_renderer/rst.py#L68), couldn't there be a work-around for ensuring the path of the files included are only from the working directory (not from anywhere in the server)?

Or would the solution be some backend tool for "package creation time" that would render the include directives only into a new .rst file that would be on the metadata?

Just trying to follow [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)

**Comment by miketheman** [comment]
Looks like a docutils feature request: https://sourceforge.net/p/docutils/feature-requests/24/

Can you share what kind of use case specifically you see would be served by this change?

**Comment by j3mdamas** [comment]
Oh, I missed that feature request.

I'm trying to support a single README.rst file that renders both on a GitHub/GitLab repository and also serve has metadata readme for packaging. I'd like to support a maintainers file (e.g., maintainters.txt) that be both used as dynamic metadata for packaging and rendered in the README file, serving as single source for both cases.

**Comment by miketheman** [comment]
Our choice is historical in nature, with little context other than supplied in the comment. 🤞 @dstufft recalls, but I wouldn't bank on it. Looks like [this thread](https://github.com/github/markup/issues/172#issuecomment-33241601) has similar concerns.

If the upstream docutils figures out a good way of handling the security concern, like that feature request proposes, I'd be very open to revisiting!

**Comment by j3mdamas** [comment]
Thanks for considering it. My current idea is to create a tool that renders includes at package build time, so that the sources have the includes, but the metadata uploaded has includes already rendered. Maybe too much work to keep it DRY, but I'll give it a try.
