### ISSUE TITLE
Convert package to PEP621 pyproject.toml

### ISSUE THREAD

**Issue by miketheman** [pypa/readme_renderer#284]
https://peps.python.org/pep-0621/
https://packaging.python.org/en/latest/specifications/declaring-project-metadata/#declaring-project-metadata

Some considerations need to be taken for  current setup.py dynamic attributes from `__about__.py`:

https://github.com/pypa/readme_renderer/blob/c6f1eabd997f4f1f2cb6edf727790c83bba3911c/setup.py#L21-L23

https://github.com/pypa/readme_renderer/blob/c6f1eabd997f4f1f2cb6edf727790c83bba3911c/setup.py#L30-L37

Some inspiration could be drawn from here: https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html#dynamic-metadata

Other values might be better served as static metadata.

**Comment by di** [comment]
Resolved by #293.
