### ISSUE TITLE
Move to PyPA org on PyPI?

### ISSUE THREAD

**Issue by webknjaz** [pypa/readme_renderer#294]
With the orgs feature on PyPI, there's a PyPA org that exists already — https://pypi.org/org/pypa/. Why not make use of it?

**Comment by miketheman** [comment]
😕, it's there already?

**Comment by di** [comment]
Yeah, it's already there: https://pypi.org/org/pypa/

**Comment by webknjaz** [comment]
Ah, I missed that. Thanks!
