### ISSUE TITLE
rst.render. Possibility to return StringIO stream ?

### ISSUE THREAD

**Issue by Carreau** [pypa/readme_renderer#30]
Would it be possible to return the stream in the following function.

https://github.com/pypa/readme/blob/master/readme/rst.py#L102-L121
Or at least return what was written to the stream.

Yes, I can pass my own stream, and that's what I'm doing for now. 

Alternatively, if not, is there a reason not to pass `os.devnull` ?

(can do a PR if one or the other seem acceptable)

**Comment by jonparrott** [comment]
Hi @Carreau, I'm not sure what exactly you wanted with this issue (or if it's even still applicable to the codebase as it is today). I'm going to close this for now, but feel free to comment if it's still relevant.

**Comment by Carreau** [comment]
Ouch it's been a while... I believe what I was hoping was changing 
https://github.com/pypa/readme_renderer/blob/b9686258d7ac3dc1314123b61b4623a916da19c4/readme_renderer/rst.py#L120-L123

Into 

```
   if rendered:
        return clean(rendered), stream # or stream.read() ?
    else:
        return None, stream # or stream.read() ?
```

To allow easy extraction of the stream object. 

If you don't you can also see that 

```
   if stream is None:
        # Use a io.StringIO as the warning stream to prevent warnings from
        # being printed to sys.stderr.
        stream = io.StringIO()
```

If wasteful unnecessary, you hold onto everything that will be written to stream while it can just be discarded. Which you can do by opening `os.devnull`

Note, you can't reopen when a maintainer closes. Up to you.

**Comment by jonparrott** [comment]
What would be the use case of extracting the stream? You have to pass it in, so you should already have a reference to it?

**Comment by Carreau** [comment]
> What would be the use case of extracting the stream? You have to pass it in, so you should already have a reference to it?

That would just allow user to not have to explicitly pass one in. I'm not interested in the stream (or writing to a stream), I'm interested as to whether there are warnings or not. Having to create, pass-in, seek(0) and read back is just incidental complexity.

Creating a mutable object to pass it in a function to read it after the function exit is also in general a concerning pattern. Moreover in this case it necessitate users to understand stream, be aware of `seek`... etc. (Not arguing whether users should know or not how to create manipulate a string, just that many do not)

As I said above you could return `stream`; or even better `stream.read()` which would be a a way better API (IMHO), at least for Python.  

> according to Uncle Bob's Clean Code.
>> Arguments are most naturally interpreted as inputs to a function.
>> Anything that forces you to check the function signature is equivalent to a double-take. It’s a cognitive break and should be avoided. In the days before object oriented programming it was sometimes necessary to have output arguments. However, much of the need for output arguments disappears in OO languages

From [here](https://softwareengineering.stackexchange.com/questions/245767/is-modifying-an-incoming-parameter-an-antipattern).

Now if that was written in C, and you were trying to minimize allocation and reuse buffers, sure. That does just seem like not pythonic and complicated.
