### ISSUE TITLE
Project name with dash instead of underscore?

### ISSUE THREAD

**Issue by reinout** [pypa/readme_renderer#39]
Many projects, I believe, use a dash in their name and an underscore for the actual code.

That'd mean `readme-renderer` as a project name and `from readme_renderer import something` in code.

The rename hasn't been released yet, I believe, so there's still time to change it. Would this be an option?

**Comment by dstufft** [comment]
The two are equivalent. PyPI and pip treat - _ and . as the same character.

**Comment by jezdez** [comment]
Closing as wontfix as the release has been done. Also while - is common in many sub communities, underscores are used as well, e.g. in the Pyramid community.
