### ISSUE TITLE
width tag not respected for images

### ISSUE THREAD

**Issue by nschloe** [pypa/readme_renderer#44]
When including images like
```rst
.. figure:: https://nschloe.github.io/quadrature/circle.svg
   :alt: 
   :width: 25.0%
```
the width tag is not respected. See, e.g., [here](https://pypi.org/project/quadpy/).

(The bug is also present in the on legacy, see [here](https://github.com/pypa/pypi-legacy/issues/547#issuecomment-258497814).)

**Comment by dstufft** [comment]
I need to check what happens if someone puts a huge image in the output here, but I think this is probably OK.

**Comment by mgedmin** [comment]
An example of this problem is https://pypi.python.org/pypi/ghcloneall.  I'm trying to shrink the asciinema-provided image to 50%, but PyPI strips my width/height attributes.  (Warehouse at least applies a max-width: 100% so it's not so bad there.)
