### ISSUE TITLE
Could the Distutils check generate an HTML document ?

### ISSUE THREAD

**Issue by Lucas-C** [pypa/readme_renderer#52]
Hi,

I tested it and this would just be a matter of adding the following at the end of https://github.com/pypa/readme_renderer/blob/master/readme_renderer/integration/distutils.py :
```
else:
    with open('long_description.html', 'w') as long_desc_file:
        long_desc_file.write(markup)
```

Now, are you OK to add this feature ?
I find it very useful to preview the description before uploading a package.

**Comment by dgasaway** [comment]
I concur. Making this change and previewing the HTML helped me find a few issues in my readme.

**Comment by di** [comment]
I think it might make more sense to add a separate command just to generate the HTML. #53 is an attempt at this, but is unfinished.
