### ISSUE TITLE
Registered as readme on PyPI

### ISSUE THREAD

**Issue by pradyunsg** [pypa/readme_renderer#56]
This package is registered as both `readme_renderer` and `readme` on PyPI.

One of them should probably be updated to say "use the other".

**Comment by gtback** [comment]
The [PyPI page for `readme`](https://pypi.org/project/readme/) says: 

> The readme library was renamed to readme_renderer to work around an installation issue that could prevent it from being installed on some systems. Use the readme_renderer library instead.

Also, installing `readme` causes the latest version of `readme-renderer` to be installed. This seems to be a deliberate decision, as discussed in #40 and implemented in ff8bf86cac2edcb141082c88217ef8ba609912f0. The 0.7.1 version of `readme` (which isn't in the `master` branch but rather the [`readme-pypi-redirect` branch](https://github.com/pypa/readme_renderer/tree/readme-pypi-redirect)) doesn't work anymore. 

(Disclaimer: I'm not a maintainer of this library, so I could be wrong about any of the above). 😃

**Comment by jonparrott** [comment]
Seems this is resolved, so I'm going to go ahead and close it.
