### ISSUE TITLE
Include docinfo table

### ISSUE THREAD

**Issue by lelit** [pypa/readme_renderer#61]
I'm used to put standard docinfo in my README.rst and thus in package's description.

The `rst.render()` function considers only the `fragment`, though, so that information does not appear on PyPI/Warehouse.

To trick it I indent the docinfo fields, so that they are rendered as a `<table>` within a `<blockquote>`: that works, but the result is somewhat ugly.

What do you think about prepending the `docinfo` part, if present?

**Comment by jonparrott** [comment]
@lelit would you mind providing an explicit example of what your source looks like and want your rendered output to look like?

**Comment by lelit** [comment]
Sure, the following is a random pick: https://raw.githubusercontent.com/lelit/pg_query/master/README.rst

As you can see, there's a (hacked) _docinfo section_ just after the subtitle: with _hacked_ I mean that it's not a real docinfo from the reST POV, as it's _indented_ by one space (and thus it's really a [block quote](http://docutils.sourceforge.net/docs/user/rst/quickref.html#block-quotes)).

The result (both on [PyPI](https://github.com/lelit/pg_query/blob/master/README.rst#pg_query) and on  [Warehouse](https://pypi.org/project/pg_query/)) is just a bit less than ideal, with that vertical line on the left...

Most docutils documentation pages have that, where it is  [rendered](http://docutils.sourceforge.net/docs/index.html) as a ``table`` with a ``docinfo`` class, which is nicer to the eye.

**Comment by jonparrott** [comment]
Thanks, @lelit! I'll try to get this fixed during my next round of changes to this project.
