### ISSUE TITLE
feature: notice if there is no long_description

### ISSUE THREAD

**Issue by brainwane** [pypa/readme_renderer#64]
We ought to warn the user about a problem if the `long_description` is entirely absent from `setup.py`.

Example: https://github.com/rytilahti/python-miio/blob/21065f696c2167e86d72f90e660a14dcef573587/setup.py has no `long_description`. But when I run readme-renderer version 17.2 in the root of that repo, in a Python 3.5.3 virtualenv, doesn't speak up about an error:

~~~
$ python setup.py check -r -s
running check
$
~~~

cc @rytilahti

**Comment by brainwane** [comment]
@di what's your take on this feature idea?

**Comment by di** [comment]
Sounds like a great idea.
