### ISSUE TITLE
GFM table: Optional whitespace next to pipes

### ISSUE THREAD

**Issue by nnadeau** [pypa/readme_renderer#78]
# Expected
The following table without spaces between the pipes is valid GitHub Flavoured Markdown, according to the following parsers:
- https://atom.io/packages/markdown-preview
- This issue's input box 

```
|Foo|Bar|
|---|---|
|FooFoo|BarBar|
```

|Foo|Bar|
|---|---|
|FooFoo|BarBar|

# Actual
```
python3 setup.py check -r -s 

warning: Check: :1: (ERROR/3) Undefined substitution referenced: "Foo|Bar".

warning: Check: Invalid markup which will not be rendered on PyPI.

error: Please correct your package.
```

# Solution
- Adding spaces next to all the pipes stops the errors:
```
| Foo | Bar |
| --- | --- |
| FooFoo | BarBar |
```

| Foo | Bar |
| --- | --- |
| FooFoo | BarBar |

- This issue probably stems from how the [GFM spec was interpreted](https://github.github.com/gfm/#tables-extension-), specifically: `[...] Spaces between pipes and cell content are trimmed [...]
  - Spaces are optional

**Comment by di** [comment]
Have you correctly set the `long_description_content_type` in your `setup.py`? The "Undefined substitution referenced" error is from the rST checker, which shouldn't be used here.

**Comment by nnadeau** [comment]
`long_description_content_type='text/markdown',`, just like in the two example repos: 
- https://github.com/jonparrott/gfm-markdown-description-example/blob/master/setup.py
- https://github.com/di/markdown-description-example/blob/master/setup.py

**Comment by nnadeau** [comment]
also:
```
Name: readme-renderer
Version: 17.4

Name: setuptools
Version: 39.0.1
```

**Comment by jonparrott** [comment]
You'll need to update to `readme-renderer >= 18.0`. We added all the fun markdown stuff in `18.0`.

**Comment by nnadeau** [comment]
```
Name: readme-renderer
Version: 18.1
```

Gives me this:

```
python3 setup.py check -r -s            
                                                                                                                    
warning: Check: :1: (ERROR/3) Undefined substitution referenced: "Foo|Bar".

warning: Check: The project's long_description has invalid markup which will not be rendered on PyPI.

error: Please correct your package.
```

**Comment by di** [comment]
Sorry, I totally forgot how the distutils integration works. The `-r` flag is for `--restructuredtext`:

```
--restructuredtext (-r)  Checks if long string meta-data syntax are
                         reStructuredText-compliant
```

It doesn't make sense to check a Markdown description with this flag. If you're using Markdown, you actually don't need to "check" your description at all -- unlike rST, it will still render as Markdown if there is anything invalid (the invalid bits just will look invalid).

We should update the documentation for this project to be more clear about when to use `check`.

**Comment by nnadeau** [comment]
Ahhh! That's it. Thanks for the help!
