### ISSUE TITLE
GFM list: Blankline required between heading and list

### ISSUE THREAD

**Issue by nnadeau** [pypa/readme_renderer#79]
# Expected
The following list without a blank space between the heading/list is valid GitHub Flavoured Markdown, according to the following parsers:
- https://atom.io/packages/markdown-preview
- This issue's input box 

```
# Heading
- Foo
- Bar
  - X
  - Y
```

# Heading
- Foo
- Bar
  - X
  - Y

# Actual
```
python3 setup.py check -r -s 

warning: Check: :4: (ERROR/3) Unexpected indentation.

warning: Check: Invalid markup which will not be rendered on PyPI.

error: Please correct your package.
```

# Solutions
- Adding a blank line under the heading
```
# Heading

- Foo
- Bar
  - X
  - Y
```

- Removing the indentation
```
# Heading
- Foo
- Bar
- X
- Y
```

**Comment by di** [comment]
Same question here as https://github.com/pypa/readme_renderer/issues/78#issuecomment-378388308.

**Comment by nnadeau** [comment]
see https://github.com/pypa/readme_renderer/issues/78#issuecomment-378391954

**Comment by nnadeau** [comment]
Solutions in:
- https://github.com/pypa/readme_renderer/issues/78#issuecomment-378392872
- https://github.com/pypa/readme_renderer/issues/78#issuecomment-378394026
