### ISSUE TITLE
Conflicting output

### ISSUE THREAD

**Issue by di** [pypa/readme_renderer#87]
When run on [this source distribution](https://files.pythonhosted.org/packages/e7/01/445b8626409505ef9ef4897cb727f3b89c11853440dd5ac3376c70eedab4/viewstate-0.4.1.tar.gz), the latest version of `readme_renderer` produces conflicting output, which indicates that the `long_description` is both valid RST, yet produces an error:

```
$ python setup.py check -r -s
running check
warning: Check: :2: (WARNING/2) Title underline too short.

warning: Check:

warning: Check: ASP.NET View State Decoder

warning: Check: ======================

warning: Check: The project's long_description has invalid markup which will not be rendered on PyPI.

The project's long description is valid RST.
error: Please correct your package.
```

**Comment by jonparrott** [comment]
Talk about mixed signals. I'll investigate this tomorrow (unless you want to beat me to it, @di).
