### ISSUE TITLE
Python 3.5 new keywords, async and await, not syntax highlighted

### ISSUE THREAD

**Issue by di** [pypa/readme_renderer#96]
From https://github.com/pypa/warehouse/issues/3770:

> See for instance https://pypi.org/project/influxdbpusher/
>
> It has code snippets  with `async def` and `await`, which are not being properly highlighted as keywords.

**Comment by jonparrott** [comment]
looks like it might just be that we need to use the "python3" lexer by default: http://pygments.org/demo/6734166/

**Comment by gjcarneiro** [comment]
I am still not seeing python 3 properly highlighted ([eg.](https://pypi.org/project/influxdbpusher/)).  Is this not deployed to pypi.org yet, or did the bug fix not work?

**Comment by theacodes** [comment]
For rst you'll need to use ``..code-block:: python3``.

**Comment by gjcarneiro** [comment]
But... it works in github as it is, see: https://github.com/GambitResearch/influxdbpusher

**Comment by theacodes** [comment]
github uses a different syntax highlighter than we do, which leads to some
inconsistencies like this. We try to match their behavior exactly when it
comes to Markdown, but so far we've only been close with RST. Do you feel
strongly we should make the RST highlighter default to python3?

**Comment by gjcarneiro** [comment]
For me, Python 3 *is* Python, Python 2 is "legacy Python".  We definitely should default to Python 3.

**Comment by theacodes** [comment]
I certainly agree with that sentiment.

@di what do you think?

**Comment by gjcarneiro** [comment]
Looks like I'm not the only package author with this problem, see https://pypi.org/project/aiokafka/0.4.3/
